DROP TABLE CP1_EMPRESA CASCADE CONSTRAINTS;

DROP TABLE CP1_CONVENIO CASCADE CONSTRAINTS;

DROP TABLE CP1_AREA_ATUACAO CASCADE CONSTRAINTS;

DROP TABLE CP1_UNIDADE CASCADE CONSTRAINTS;

DROP TABLE CP1_ENDERECO_UNIDADE CASCADE CONSTRAINTS;

DROP TABLE CP1_MEDICO_UNIDADE CASCADE CONSTRAINTS;

DROP TABLE CP1_MEDICO CASCADE CONSTRAINTS;

DROP TABLE CP1_CLIENTE CASCADE CONSTRAINTS;

DROP TABLE CP1_ENDERECO_CLIENTE CASCADE CONSTRAINTS;

DROP TABLE CP1_COMORBIDADE CASCADE CONSTRAINTS;

DROP TABLE CP1_HISTORICO_SAUDE_CLIENTE CASCADE CONSTRAINTS;

DROP TABLE CP1_HISTORICO_HOSPITAL_CLIENTE CASCADE CONSTRAINTS;

DROP TABLE CP1_CIDADE CASCADE CONSTRAINTS;

DROP TABLE CP1_ESTADO CASCADE CONSTRAINTS;

DROP TABLE CP1_ESTADO_CIVIL CASCADE CONSTRAINTS;

DROP TABLE AUDITORIA_CP1_EMPRESA CASCADE CONSTRAINTS;

DROP SEQUENCE CP1_ESTADO_SEQ;

DROP SEQUENCE CP1_CIDADE_SEQ;

DROP SEQUENCE CP1_ESTADO_CIVIL_SEQ;

DROP SEQUENCE CP1_EMPRESA_SEQ;

DROP SEQUENCE CP1_CONVENIO_SEQ;

DROP SEQUENCE CP1_AREA_ATUACAO_SEQ;

DROP SEQUENCE CP1_UNIDADE_SEQ;

DROP SEQUENCE CP1_ENDERECO_UNIDADE_SEQ;

DROP SEQUENCE CP1_MEDICO_SEQ;

DROP SEQUENCE CP1_MEDICO_UNIDADE_SEQ;

DROP SEQUENCE CP1_CLIENTE_SEQ;

DROP SEQUENCE CP1_ENDERECO_CLIENTE_SEQ;

DROP SEQUENCE CP1_COMORBIDADE_SEQ;

DROP SEQUENCE CP1_HISTORICO_SAUDE_CLIENTE_SEQ;

DROP SEQUENCE CP1_HISTORICO_HOSPITAL_CLIENTE_SEQ;

DROP SEQUENCE AUDITORIA_CP1_EMPRESA_SEQ;

CREATE SEQUENCE CP1_ESTADO_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_CIDADE_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_EMPRESA_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_CONVENIO_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_AREA_ATUACAO_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_UNIDADE_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_ENDERECO_UNIDADE_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_MEDICO_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_MEDICO_UNIDADE_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_ESTADO_CIVIL_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_CLIENTE_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_ENDERECO_CLIENTE_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_COMORBIDADE_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_HISTORICO_SAUDE_CLIENTE_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CP1_HISTORICO_HOSPITAL_CLIENTE_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE AUDITORIA_CP1_EMPRESA_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE CP1_ESTADO (
    ID NUMBER DEFAULT CP1_ESTADO_SEQ.NEXTVAL PRIMARY KEY,
    NOME VARCHAR(20)
);

CREATE TABLE CP1_CIDADE (
    ID NUMBER DEFAULT CP1_CIDADE_SEQ.NEXTVAL PRIMARY KEY,
    NOME VARCHAR(20),
    ESTADO_ID NUMBER,
    FOREIGN KEY (ESTADO_ID) REFERENCES CP1_ESTADO(ID)
);

CREATE TABLE CP1_EMPRESA (
    ID NUMBER DEFAULT CP1_EMPRESA_SEQ.NEXTVAL PRIMARY KEY,
    CNPJ VARCHAR(20),
    NOME VARCHAR(100),
    TIPO VARCHAR(100),
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100)
);

CREATE TABLE CP1_CONVENIO (
    ID NUMBER DEFAULT CP1_CONVENIO_SEQ.NEXTVAL PRIMARY KEY,
    EMPRESA_ID NUMBER,
    NOME VARCHAR(100),
    VALOR FLOAT(53),
    TIPO_SERVICO VARCHAR(100),
    COBERTURA VARCHAR(100),
    CONTATO VARCHAR(100),
    VALIDADE DATE,
    FOREIGN KEY (EMPRESA_ID) REFERENCES CP1_EMPRESA(ID)
);

CREATE TABLE CP1_AREA_ATUACAO (
    ID NUMBER DEFAULT CP1_AREA_ATUACAO_SEQ.NEXTVAL PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE CP1_UNIDADE (
    ID NUMBER DEFAULT CP1_UNIDADE_SEQ.NEXTVAL PRIMARY KEY,
    EMPRESA_ID NUMBER,
    AREA_ATUACAO_ID NUMBER,
    NOME VARCHAR(100),
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    TIPO VARCHAR(100),
    CAPACIDADE NUMBER,
    FOREIGN KEY (EMPRESA_ID) REFERENCES CP1_EMPRESA(ID),
    FOREIGN KEY (AREA_ATUACAO_ID) REFERENCES CP1_AREA_ATUACAO(ID)
);

CREATE TABLE CP1_ENDERECO_UNIDADE (
    ID NUMBER DEFAULT CP1_ENDERECO_UNIDADE_SEQ.NEXTVAL PRIMARY KEY,
    UNIDADE_ID NUMBER UNIQUE NOT NULL,
    RUA VARCHAR(100),
    NUMERO VARCHAR(10),
    CEP VARCHAR(20),
    CIDADE_ID NUMBER,
    FOREIGN KEY (UNIDADE_ID) REFERENCES CP1_UNIDADE(ID),
    FOREIGN KEY (CIDADE_ID) REFERENCES CP1_CIDADE(ID)
);

CREATE TABLE CP1_MEDICO (
    ID NUMBER DEFAULT CP1_MEDICO_SEQ.NEXTVAL PRIMARY KEY,
    NOME VARCHAR(100),
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    ESPECIALIDADE VARCHAR(100),
    CRM VARCHAR(20)
);

CREATE TABLE CP1_MEDICO_UNIDADE (
    ID NUMBER DEFAULT CP1_MEDICO_UNIDADE_SEQ.NEXTVAL PRIMARY KEY,
    MEDICO_ID NUMBER NOT NULL,
    UNIDADE_ID NUMBER NOT NULL,
    HORARIO_ATENDIMENTO VARCHAR(100),
    FOREIGN KEY (MEDICO_ID) REFERENCES CP1_MEDICO(ID),
    FOREIGN KEY (UNIDADE_ID) REFERENCES CP1_UNIDADE(ID)
);

CREATE TABLE CP1_ESTADO_CIVIL (
    ID NUMBER DEFAULT CP1_ESTADO_CIVIL_SEQ.NEXTVAL PRIMARY KEY,
    NOME VARCHAR(20)
);

CREATE TABLE CP1_CLIENTE (
    ID NUMBER DEFAULT CP1_CLIENTE_SEQ.NEXTVAL PRIMARY KEY,
    RG VARCHAR(20),
    NOME VARCHAR(100),
    SEXO CHAR(1) CHECK (SEXO IN ('M', 'F', 'O')),
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    DATA_NASCIMENTO DATE,
    CPF VARCHAR(20),
    CONVENIO_ID NUMBER,
    ESTADO_CIVIL_ID NUMBER,
    FOREIGN KEY (CONVENIO_ID) REFERENCES CP1_CONVENIO(ID),
    FOREIGN KEY (ESTADO_CIVIL_ID) REFERENCES CP1_ESTADO_CIVIL(ID)
);

CREATE TABLE CP1_ENDERECO_CLIENTE (
    ID NUMBER DEFAULT CP1_ENDERECO_CLIENTE_SEQ.NEXTVAL PRIMARY KEY,
    CLIENTE_ID NUMBER UNIQUE NOT NULL,
    RUA VARCHAR(100),
    NUMERO VARCHAR(10),
    CEP VARCHAR(20),
    CIDADE_ID NUMBER,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CP1_CLIENTE(ID),
    FOREIGN KEY (CIDADE_ID) REFERENCES CP1_CIDADE(ID)
);

CREATE TABLE CP1_COMORBIDADE (
    ID NUMBER DEFAULT CP1_COMORBIDADE_SEQ.NEXTVAL PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE CP1_HISTORICO_SAUDE_CLIENTE (
    ID NUMBER DEFAULT CP1_HISTORICO_SAUDE_CLIENTE_SEQ.NEXTVAL PRIMARY KEY,
    CLIENTE_ID NUMBER UNIQUE NOT NULL,
    COMORBIDADE_ID NUMBER,
    DATA_REGISTRO DATE,
    FUMA NUMBER(1) CHECK (FUMA IN (0, 1)),
    OBSERVACOES VARCHAR(100),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CP1_CLIENTE(ID),
    FOREIGN KEY (COMORBIDADE_ID) REFERENCES CP1_COMORBIDADE(ID)
);

CREATE TABLE CP1_HISTORICO_HOSPITAL_CLIENTE (
    ID NUMBER DEFAULT CP1_HISTORICO_HOSPITAL_CLIENTE_SEQ.NEXTVAL PRIMARY KEY,
    CLIENTE_ID NUMBER UNIQUE NOT NULL,
    DATA_REGISTRO DATE,
    HISTORICO_MEDICO VARCHAR(100),
    EXAMES_REALIZADOS VARCHAR(100),
    MEDICAMENTOS_PRESCRITOS VARCHAR(100),
    OBSERVACOES VARCHAR(100),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CP1_CLIENTE(ID)
);

CREATE TABLE AUDITORIA_CP1_EMPRESA (
    ID NUMBER PRIMARY KEY,
    OPERACAO VARCHAR(10),
    DATA_OPERACAO DATE,
    USUARIO VARCHAR(50),
    CNPJ_OLD VARCHAR(20),
    NOME_OLD VARCHAR(100),
    TIPO_OLD VARCHAR(100),
    TELEFONE_OLD VARCHAR(20),
    EMAIL_OLD VARCHAR(100),
    CNPJ_NEW VARCHAR(20),
    NOME_NEW VARCHAR(100),
    TIPO_NEW VARCHAR(100),
    TELEFONE_NEW VARCHAR(20),
    EMAIL_NEW VARCHAR(100)
);